name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Или ваша ветка, где вы хотите собирать документацию

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Это нужно, чтобы GitHub Actions могли делать коммиты
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Укажите версию Python, необходимую для вашего проекта

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Убедитесь, что у вас есть файл requirements.txt со всеми зависимостями

      - name: Build Sphinx Documentation
        run: |
          cd docs  # Предполагается, что ваша Sphinx конфигурация находится в папке docs
          make html

      - name: Copy Sphinx HTML to /docs folder
        run: |
          # Убедитесь, что /docs уже есть в вашем репозитории
          rm -rf /docs/*  # Очистите текущее содержимое
          cp -R _build/html/* /docs

      - name: Commit and Push changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add /docs
          git commit -m "Update documentation"
          git push
